export const CAMPAIGN_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED",
  GOAL_REACHED: "GOAL_REACHED",
  CLOSED: "CLOSED",
}

export const KYC_STATUS = {
  NONE: "NONE",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
}

export const DISBURSEMENT_STATUS = {
  PENDING_VERIFY: "PENDING_VERIFY",
  COMPLETED: "COMPLETED",
}

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
}

export const BLOCKCHAIN_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  IGNORED: "IGNORED",
}

export const USER_ROLE = {
  USER: "USER",
  ADMIN: "ADMIN",
}

export const ACCOUNT_TYPE = {
  INDIVIDUAL: "INDIVIDUAL",
  ORGANIZATION: "ORGANIZATION",
}
