/**
 * Enumeration constants for all entities
 */

const USER_ROLE = {
  USER: 'USER',
  ADMIN: 'ADMIN',
}

const ACCOUNT_TYPE = {
  INDIVIDUAL: 'INDIVIDUAL',
  ORGANIZATION: 'ORGANIZATION',
}

const KYC_STATUS = {
  NONE: 'NONE',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}

const CAMPAIGN_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
  GOAL_REACHED: 'GOAL_REACHED',
  CLOSED: 'CLOSED',
}

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
}

const DISBURSEMENT_STATUS = {
  PENDING_TRANSFER: 'PENDING_TRANSFER',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
}

const BLOCKCHAIN_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  IGNORED: 'IGNORED',
}

module.exports = {
  USER_ROLE,
  ACCOUNT_TYPE,
  KYC_STATUS,
  CAMPAIGN_STATUS,
  PAYMENT_STATUS,
  DISBURSEMENT_STATUS,
  BLOCKCHAIN_STATUS,
}
